baseurl: localhost:1313
title: BouwBureau Brok | Bouwkundig tekenen & constructief tekenen
languageCode: en-us
theme: hugo-elate-theme
params:

  # Meta ---- 
  
  author: ''
  icon: images/favicon.ico
  logo: images/bbb_main.png
  avatar: images/bbb_main.png
  custom_css:
    - css/custom1.css
    - css/custom2.css
  description: 'Wij zijn een betrouwbaar en flexibel adviesbureau dat sinds 2014 gespecialiseerd is in het maken van constructieve berekeningen. Wij geven constructieve adviezen in staal-, hout, beton en metselwerkconstructies gericht op de woning en utiliteitsbouw.'
  email: 'stefan@chartwise.nl'
  
  # Navigation ---
  # You can add custom links before or after the default links
  # Assign a weight to define the order
  
  # prepended links
  #[[menu.prepend]]
  #  url = "http://gohugo.io"
  #  name = "Hugo"
  #  weight = 10

  # postpended links
  #[[menu.postpend]]
  #  url = "http://gohugo.io"
  #  name = "External link"
  #  weight = 10

  navigation:
    about: Over
    brand: Bouwbureau Brok
    contact: Offerte aanvragen
    home: Home
    services: Services
    testimonials: Reviews
    work: Diensten
  
  # Hero section ----
  hero:
    title: Constructie berekening nodig?
    subtitle: '✓ Levertijd vaak binnen 2 weken </br>
    ✓ Lage prijzen door lage onkosten </br>
    ✓ Erkend en verzekerd constructeursbureau'
   
  # Intro section ---- 
  # Available icons: https://icomoon.io/#preview-free
  intro:
    item:
      - button: Bekijk diensten
        description: Bekijk hier de constructieve mogelijkheden en huidige prijzen.
        icon: icon-briefcase
        img: img_7.jpg
        title: Diensten
        url: '#fh5co-work'
      - button: Offerte aanvragen
        description: 'Snel een vrijblijvende offerte aanvragen? 
        Gratis offerte binnen 48 uur.'
        icon: icon-pencil
        img: img_8.jpg
        title: Offerte aanvragen
        url: '#contact'
      - button: Neem contact op
        description: 'Heb je nog overige vragen? Bel of mail ons dan direct.'
        icon: icon-envelope
        img: img_10.jpg
        title: Contact
        url: 'mailto:s.brok@bouwbureaubrok.nl'
        
    video:
      title: Watch the video
      enable: no
      icon: icon-play2
      url: https://vimeo.com/channels/staffpicks/93951774
  
  # Work section ----
  work:
    title: Diensten
    description: 'Wij zijn een betrouwbaar en flexibel adviesbureau dat sinds 2014
    gespecialiseerd is in het maken van constructieve berekeningen. 
    Wij geven constructieve adviezen in staal-, hout, beton en metselwerkconstructies 
    gericht op de woning en utiliteitsbouw. Kijk eens op onze prijzen indicaties.'
    enable: yes
    footertext: ''
    row:
      - alt: Image2
        img: diensten/aanbouw.jpg
        subtitle: 'Het maken van een constructie berekening om een draagmuur te verwijderen.'
        price: Vanaf €332,75 incl. btw.
        title: Draagmuur verwijderen
      - alt: Image2
        img: diensten/aanbouw.jpg
        subtitle: 'Het maken van een constructie berekening om een aanbouw of opbouw te plaatsen.'
        price: Vanaf €532,40 incl. btw.
        title: Aanbouw plaatsen
      - alt: Image3
        img: diensten/aanbouw.jpg
        subtitle: 'Het maken van een constructie berekening om een nieuwe woning te bouwen.'
        price: Vanaf €798,60 incl. btw.
        title: Nieuwe woningbouwen
      - alt: Image4
        img: diensten/aanbouw.jpg
        subtitle: 'Stalen hallen, bedrijfsgebouwen en stalen platformen berekenen 
        doen wij erg graag. We beschikken over een 3D staal reken programma waarmee 
        wij eenvoudig de meest complexe 3D staal berekeningen kunnen maken. 
        Een stalen entresol berekening start al vanaf 532,40 maar vraag eens naar de 
        oneindige staal mogelijkheden binnen ons bedrijf.'
        price: Vanaf €532,40 incl. btw.
        title: 3D Staalconstructie 
      - alt: Image5
        img: diensten/aanbouw.jpg
        subtitle: 'Denk hierbij aan een enkele vloer berekening, gordingen
        berekening of houten balklaag berekening. Ook het berekenen van uw 
        bestaande dak voor nieuwe zonnepanelen, kunt u door ons laten berekenen.'
        price: Vanaf €199,65 incl. btw.
        title: Overige constructieve aanpassingen
      - alt: Image6
        img: diensten/aanbouw.jpg
        subtitle: 'Wij hanteren een uur tarief van 55 euro excl. btw. met een 
        start van 3 uur in verband met administratieve verwerkingen. 
        Doordat wij een klein adviesbureau zijn zonder kantoor en dure software
        kunnen wij een laag tarief aanhouden.'
        price: Uur tarief van €55,- excl. btw.
        title: Op uurbasis
  
  # Testimonials section ----
  testimonials:
    title: Wat klanten zeggen
    description: Far far away, behind the word mountains, far from the countries Vokalia
      and Consonantia, there live the blind texts.
    enable: no
    item:
      - alt: Person1
        img: person1.jpg
        person: Jean Doe, CEO <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a>
          <span class="subtext">Creative Director</span>
        quote: '&ldquo;Far far away, behind the word mountains, far from the countries
          Vokalia and Consonantia, there live the blind texts. Separated they live
          in Bookmarksgrove right at the coast of the Semantics, a large language
          ocean.&rdquo;'
      - alt: Person2
        img: person2.jpg
        person: John Doe, Senior UI <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a>
          <span class="subtext">Creative Director</span>
        quote: '&ldquo;Far far away, behind the word mountains, far from the countries
          Vokalia and Consonantia, there live the blind texts. Separated they live
          in Bookmarksgrove right at the coast of the Semantics, a large language
          ocean. Far far away, behind the word mountains, far from the countries Vokalia
          and Consonantia, there live the blind texts.&rdquo;'
      - alt: Person3
        img: person3.jpg
        person: Chris Nash, Director <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a>
          <span class="subtext">Creative Director</span>
        quote: '&ldquo;Far far away, behind the word mountains, far from the countries
          Vokalia and Consonantia, there live the blind texts. &rdquo;'
  
  # Services section ----
  services:
    title: Services
    description: Far far away, behind the word mountains, far from the countries Vokalia
      and Consonantia, there live the blind texts.
    enable: no
    item:
      - description: Far far away, behind the word mountains, far from the countries
          Vokalia and Consonantia, there live the blind texts. Separated they live
          in Bookmarksgrove right at the coast of the Semantics, a large language
          ocean
        icon: icon-anchor
        title: Brand &amp; Strategy
      - description: Far far away, behind the word mountains, far from the countries
          Vokalia and Consonantia, there live the blind texts. Separated they live
          in Bookmarksgrove right at the coast of the Semantics, a large language
          ocean
        icon: icon-layers2
        title: Web &amp; Interface
      - description: Far far away, behind the word mountains, far from the countries
          Vokalia and Consonantia, there live the blind texts. Separated they live
          in Bookmarksgrove right at the coast of the Semantics, a large language
          ocean
        icon: icon-video2
        title: Photo &amp; Video
      - description: Far far away, behind the word mountains, far from the countries
          Vokalia and Consonantia, there live the blind texts. Separated they live
          in Bookmarksgrove right at the coast of the Semantics, a large language
          ocean
        icon: icon-monitor
        title: CMS &amp; eCommerce
  
  # About section ----  
  about:
    title: About
    description: Far far away, behind the word mountains, far from the countries Vokalia
      and Consonantia, there live the blind texts.
    enable: no
    item:
      - alt: Person1
        description: Far far away, behind the word mountains, far from the countries
          Vokalia and Consonantia, there live the blind texts
        img: person1.jpg
        name: Jean Smith
        position: Web Designer
        social:
          - - icon-twitter
            - '#'
          - - icon-facebook
            - '#'
          - - icon-linkedin
            - '#'
      - alt: Person2
        description: Far far away, behind the word mountains, far from the countries
          Vokalia and Consonantia, there live the blind texts
        img: person2.jpg
        name: Rob Smith
        position: Web Developer
        social:
          - - icon-twitter
            - '#'
          - - icon-facebook
            - '#'
          - - icon-github
            - '#'
      - alt: Person3
        description: Far far away, behind the word mountains, far from the countries
          Vokalia and Consonantia, there live the blind texts
        img: person3.jpg
        name: Larry Ben
        position: Web Designer
        social:
          - - icon-twitter
            - '#'
          - - icon-facebook
            - '#'
          - - icon-dribbble
            - '#'
  
  # Counters section ----
  counters:
    title: Erkend constructiebureau sinds 2014
    background: stats.jpg
    enable: yes
    item:
      - description: Tevreden Klanten
        from: 0
        icon: icon-people
        interval: 50
        speed: 3000
        to: 89
      - description: Aantal Projecten
        from: 0
        icon: icon-cog
        interval: 50
        speed: 3000
        to: 200
      - description: Aantal Bouwtekeningen
        from: 0
        icon: icon-file-text-o
        interval: 50
        speed: 3000
        to: 140
      - description: Aantal Berekeningen
        from: 0
        icon: icon-calculator
        interval: 50
        speed: 3000
        to: 300
  
  
  # Contact section ----
  contact:
    button: Stuur bericht
    description: "Door het toevoegen van tekeningen, berekeningen en foto's
    kunnen wij een beter beeld krijgen van de situatie en een betere offerte voor je maken."

    details:
      - - icon-home
        - Boogschutter 44 <br> 5482 SL Schijndel, <br> Nederland
      - - icon-phone
        - 0416-776757
      - - icon-envelope
        - info@bouwbureaubrok.nl
      - - icon-briefcase
        - Kvk - 61517666
    enable: yes
    form: yes
    map: yes
    message: Geef een beknopte omschrijving van de werkzaamheden.
    name: Naam
    address: Straat + huisnummer*
    postcode: Postcode
    city: Woonplaats
    phone: Telefoon Nr.
    email: Email*
    type: Type project
    files: Voeg bestanden toe
    title: Vraag offerte aan
  
  # Footer section ----
  footer:
    copyright: '© Bouwbureau Brok. All rights reserved.'
    enable: yes
    links:
      - - icon-twitter
        - '#twitter'
      - - icon-facebook
        - '#facebook'
      - - icon-linkedin
        - 'https://www.linkedin.com/in/steven-brok-15a0ba59/'
  googleMapsApiKey: ''
  
markup:
  goldmark:
    renderer:
      unsafe: true
